name: upnp_explorer
description: Discover and control UPnP devices.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.4.2+17

environment:
  sdk: '>=2.18.0 <3.3.0'

dependencies:
  bloc: ^8.1.1
  connectivity_plus: ^3.0.0
  device_info_plus: ^8.0.0
  diffutil_dart: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  in_app_review: ^2.0.4
  injectable: ^2.1.0
  intl: ^0.18.0
  open_settings: ^2.0.2
  package_info_plus: ^3.0.1
  shared_preferences: ^2.0.17
  string_validator: ^1.0.0
  url_launcher: ^6.1.8
  xml: ^6.2.2
  rxdart: ^0.27.7
  animated_list_plus: ^0.5.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  mockito: ^5.3.2
  test: ^1.22.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/CHANGELOG.md