name: upnp_explorer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+10

environment:
  sdk: '>=2.18.0 <3.3.0'

dependencies:
  bloc: ^8.1.0
  connectivity_plus: ^3.0.0
  device_info_plus: ^8.0.0
  diffutil_dart: ^3.0.0
  equatable: ^2.0.5
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  in_app_review: ^2.0.4
  injectable: ^1.5.3
  intl: ^0.17.0
  open_settings: ^2.0.2
  package_info_plus: ^3.0.1
  shared_preferences: ^2.0.8
  string_validator: ^0.3.0
  url_launcher: ^6.1.6
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  mockito: ^5.3.2
  test: ^1.22.0

flutter:
  uses-material-design: true
  assets:
    - assets/changes.json
    - assets/google_fonts/
    - assets/automatic_animated_list/
flutter_intl:
  enabled: true
  arb_dir: lib/application/l10n
  output_dir: lib/application/l10n/generated
